# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TheSocialClub' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TheSocialClub
   pod 'Parse'
   pod 'AlamofireImage'

  target 'TheSocialClubTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TheSocialClubUITests' do
    # Pods for testing
  end

end
